site_name: Ordinary Differential Equations 

theme:
  name: readthedocs

plugins:
  - mkdocstrings
  - search

nav:
  - index.md
  - reference.md

use_directory_urls: false

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math
